### PR TITLE
Incoming commands

### PR DESCRIPTION
**Pull request by david50407**
Hey there, I implement the Slack outgoing webhook server.
And this PR is based on #7 I send.

### CODE REVIEW

**Comment by mastercoms** [comment]
Thank you a lot for this. Looks good with a quick glance, I am going to change a bit of the code and review it more over this weekend. Again, THANK YOU.

**Comment by mastercoms** [comment]
Could you explain your reasoning for jetty? Not disagreeing with you, just want to see why you choose it and if we can discuss alternatives to make sure we include the best option for Slack.

**Comment by mastercoms** [comment]
Alright, I merged this, just to mark progress but this pull request isn't done yet because we're going to have to change some stuff.

**Comment by mastercoms** [comment]
I will be rewriting this based on your contributions. Thanks!

**Comment by david50407** [comment]
`Dynmap` also use jetty so I think it's ok for bukkit plugins.

**Comment by mastercoms** [comment]
Ok.

**Pull request closed without merging**
